name: 'Download new data'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 03:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Upgrade, intall dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_download.txt

      - name: Run script, commit
        run: python save_new_data.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "new data downloaded"
          git push
