name: 'Download new data'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 03:00 every day

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      
    steps:
      - uses: actions/checkout@v4 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Upgrade, intall dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_download.txt

      - name: Run script 
        run: python -m scripts.save_new_data  # run as a module

      - name: Autocommit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Download new data
